"""Initial database schema with SQLite support

Revision ID: 2f5ea2158676
Revises: 
Create Date: 2026-07-03 01:03:02.587674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5ea2158676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=50), nullable=True),
    sa.Column('youtube_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('discovery_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('independence_status', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_index(op.f('ix_artists_spotify_id'), 'artists', ['spotify_id'], unique=True)
    op.create_index(op.f('ix_artists_youtube_id'), 'artists', ['youtube_id'], unique=True)
    op.create_table('artist_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('metric_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_metrics_artist_id'), 'artist_metrics', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artist_metrics_id'), 'artist_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_artist_metrics_time'), 'artist_metrics', ['time'], unique=False)
    op.create_table('authenticity_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('confidence', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authenticity_signals_id'), 'authenticity_signals', ['id'], unique=False)
    op.create_table('daily_scores',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('momentum_score', sa.Integer(), nullable=True),
    sa.Column('authenticity_score', sa.Integer(), nullable=True),
    sa.Column('cultural_score', sa.Integer(), nullable=True),
    sa.Column('commercial_score', sa.Integer(), nullable=True),
    sa.Column('breakout_probability', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('urgency_level', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('date', 'artist_id')
    )
    op.create_table('intelligence_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('human_reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_reports_id'), 'intelligence_reports', ['id'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('spotify_id', sa.String(length=50), nullable=True),
    sa.Column('youtube_id', sa.String(length=50), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('isrc', sa.String(length=20), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.create_index(op.f('ix_songs_spotify_id'), 'songs', ['spotify_id'], unique=False)
    op.create_table('playlist_placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.String(length=50), nullable=False),
    sa.Column('playlist_name', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('placement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('playlist_followers', sa.Integer(), nullable=True),
    sa.Column('is_editorial', sa.Boolean(), nullable=True),
    sa.Column('curator_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_placements_id'), 'playlist_placements', ['id'], unique=False)
    op.create_table('song_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('metric_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_metrics_id'), 'song_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_song_metrics_song_id'), 'song_metrics', ['song_id'], unique=False)
    op.create_index(op.f('ix_song_metrics_time'), 'song_metrics', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_metrics_time'), table_name='song_metrics')
    op.drop_index(op.f('ix_song_metrics_song_id'), table_name='song_metrics')
    op.drop_index(op.f('ix_song_metrics_id'), table_name='song_metrics')
    op.drop_table('song_metrics')
    op.drop_index(op.f('ix_playlist_placements_id'), table_name='playlist_placements')
    op.drop_table('playlist_placements')
    op.drop_index(op.f('ix_songs_spotify_id'), table_name='songs')
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_intelligence_reports_id'), table_name='intelligence_reports')
    op.drop_table('intelligence_reports')
    op.drop_table('daily_scores')
    op.drop_index(op.f('ix_authenticity_signals_id'), table_name='authenticity_signals')
    op.drop_table('authenticity_signals')
    op.drop_index(op.f('ix_artist_metrics_time'), table_name='artist_metrics')
    op.drop_index(op.f('ix_artist_metrics_id'), table_name='artist_metrics')
    op.drop_index(op.f('ix_artist_metrics_artist_id'), table_name='artist_metrics')
    op.drop_table('artist_metrics')
    op.drop_index(op.f('ix_artists_youtube_id'), table_name='artists')
    op.drop_index(op.f('ix_artists_spotify_id'), table_name='artists')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###